esphome:
  name: c3-0

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
    version: recommended

# Enable logging
logger:

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "RedBrick Waddles"
  password: "Daisy-Donaldo-Quacks?"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "C3-0 Fallback Hotspot"
    password: "a5TrGfz9KA7W"

captive_portal:

mqtt:
  broker: 10.42.206.199
  port: 1883
  birth_message:
    topic: "test"
    payload: "C3-0 is online"

sensor:
  - platform: internal_temperature
    name: "ESP32 Internal Temperature"
    id: internal_temp_sensor
    update_interval: 30s
    on_value:
      then:
        - logger.log:
            format: "Internal Temp: %.1f"
            args: ["id(internal_temp_sensor).state"]
        - mqtt.publish:
            topic: "test"
            payload: !lambda |-
              return "c3-0 temp:" + std::to_string(id(internal_temp_sensor).state);
        # service: mqtt.publish
        # data:
        #   topic: "test"
        #   payload: id(internal_temp_sensor).state
